version : "3"
services :
    mongocontainer :
        image : mongo
        container_name : "mongocontainer"
        ports :
          - 27017:27017
    springboot-mongodb :
      image : springboot
      container_name : springboot-mongodb
      ports :
        - 8080:8080
      links :
        - mongocontainer